/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContratsRouteImport } from './routes/contrats'
import { Route as IndexRouteImport } from './routes/index'

const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratsRoute = ContratsRouteImport.update({
  id: '/contrats',
  path: '/contrats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contrats': typeof ContratsRoute
  '/equipe': typeof EquipeRoute
  '/interventions': typeof InterventionsRoute
  '/prospects': typeof ProspectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contrats': typeof ContratsRoute
  '/equipe': typeof EquipeRoute
  '/interventions': typeof InterventionsRoute
  '/prospects': typeof ProspectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contrats': typeof ContratsRoute
  '/equipe': typeof EquipeRoute
  '/interventions': typeof InterventionsRoute
  '/prospects': typeof ProspectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contrats' | '/equipe' | '/interventions' | '/prospects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contrats' | '/equipe' | '/interventions' | '/prospects'
  id:
    | '__root__'
    | '/'
    | '/contrats'
    | '/equipe'
    | '/interventions'
    | '/prospects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContratsRoute: typeof ContratsRoute
  EquipeRoute: typeof EquipeRoute
  InterventionsRoute: typeof InterventionsRoute
  ProspectsRoute: typeof ProspectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrats': {
      id: '/contrats'
      path: '/contrats'
      fullPath: '/contrats'
      preLoaderRoute: typeof ContratsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContratsRoute: ContratsRoute,
  EquipeRoute: EquipeRoute,
  InterventionsRoute: InterventionsRoute,
  ProspectsRoute: ProspectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
